name: Hello World Workflow

on:
  push:


jobs:
  hello_world:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, World from GitHub Actions!"
